### ISSUE TITLE
Mailbox is created if mailbox limit configuration is 0

### ISSUE THREAD

**Issue by harobed** [modoboa/modoboa-admin-limits#6]
When DomainAdmin user try to append account (Add account link) and mailbox limit configuration is 0 then : 

* « Mailboxes: limit reached » message is display, this is right
* but mailbox is created ! <= this is bug

**Comment by harobed** [comment]
Here when check is executed, mailbox is already created : https://github.com/modoboa/modoboa-admin-limits/blob/master/modoboa_admin_limits/controls.py#L129

**Comment by tonioo** [comment]
See https://github.com/tonioo/modoboa/issues/740.
